# Generated by Django 5.0 on 2025-07-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransaction',
            name='related_redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rewards.redemption'),
        ),
    ]
