# Generated by Django 5.0 on 2025-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recycling bin',
                'verbose_name_plural': 'Recycling bins',
                'indexes': [models.Index(fields=['active'], name='bins_bin_active_04717c_idx')],
            },
        ),
    ]
