# Generated by Django 5.0 on 2025-07-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_trash', models.BooleanField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bins.bin')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
