# Generated by Django 5.0 on 2025-07-04 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['user', 'created_at'], name='scans_scane_user_id_ce8488_idx'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['bin', 'created_at'], name='scans_scane_bin_id_4b4629_idx'),
        ),
    ]
