# Generated by Django 5.0 on 2025-07-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanevent',
            name='is_trash',
        ),
        migrations.AddField(
            model_name='scanevent',
            name='image',
            field=models.ImageField(default=1, upload_to='scans/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanevent',
            name='trash_type',
            field=models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('glass', 'Glass'), ('paper', 'Paper'), ('unsorted', 'Unsorted')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scanevent',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
